runtime: python37
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  gcp_project: [REPLACE WITH GCP PROJECT ID]
  gcp_topic: [REPLACE WITH GCP TOPIC]
  news_query: 'REPLACE WITH QUERY'
  # TO DO: use runtime config to set API key
  newsapi_key: [REPLACE WITH API KEY]
