runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 300

runtime_config:
    python_version: 3

resources:
 disk_size_gb: 40
 memory_gb: 4

handlers:
- url: /predict
  static_dir: static/predict
  http_headers:
    Access-Control-Allow-Origin: '*'
