runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 300

runtime_config:
    python_version: 3

resources:
 disk_size_gb: 40

handlers:
- url: /prediction
  static_dir: static/prediction
  http_headers:
    Access-Control-Allow-Origin: '*'
